apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: orbitflow
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9yaXRpa3N1dGVyaTpyaXRpazEyM0BjbHVzdGVyMC44Y3l0bS5tb25nb2RiLm5ldA==
  JWT_SECRET: Y2hhaWF1cmNvZGVrZXNhdGg=
  EMAIL: cml0aWtzdXRlcmlAZ21haWwuY29t
  EMAIL_PASS: bWFxdSBzdndvIGxmaGEgeWF5bw==
  ARCJET_KEY: YWprZXlfMDFrNnE1OHM3YmVrNThkbmt4MXczdmNzaGM=